---
- name: Cloning emacs config from github 
  git:
    repo: 'https://github.com/hephaex/emacs_config.git'
    dest: ~/Simon/github/emacs_config
    clone: yes
    update: yes

- name: Making simbolic link for emacs
  file:
    src: '~/Simon/github/emacs_config/.emacs.d'
    dest: '~/.emacs.d'
    state: link

- name: Installing emacs
  homebrew_cask:
    name: emacs
    state: present

- name: Making alias for emacs shell
  blockinfile:
    path: "{{ ansible_facts.user_dir }}/{{ item }}"
    state: present
    # insertafter is skiped
    marker: "##### {mark} emacs alias #####"
    content: |
      alias emacs='/usr/local/bin/emacs -nw'
  with_items:
    #- .bashrc
    #- .profile
    - .bash_profile

- name: Installing python related packages
  pip:
    requirements: ~/Simon/github/emacs_config/python_debug.txt
    executable: pip3

