- name: Setup default git configuraiton
  git_config:
    name="{{ item.name }}"
    scope=global
    value="{{ item.value }}"
  with_items:
    - {name: "user.name",  value: "{{ git_user }}" }
    - {name: "user.email", value: "{{ git_email }}" }
    - {name: "core.precomposeunicode", value: 'true'}
    - {name: "core.quotepath", value: 'false'}
    - {name: "ui.color",   value: 'true' }
    - {name: "core.editor", value: "emacs" }
