- name: Setup default git configuraiton
  git_config:
    name="{{ item.name }}"
    scope=global
    value="{{ item.value }}"
  with_items:
    - {name: "user.name",  value: "{{ git_user }}" }
    - {name: "user.email", value: "{{ git_email }}" }
    - {name: "ui.color",   value: True }
    - {name: "core.editor", value: "emacs" }